schema_version: 20180708
name: configuration-variable
version: 0.0.13
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.87
run_image: fnproject/fn-java-fdk:jre11-1.0.87
cmd: com.example.fn.ConfigurationVariable::hello
triggers:
- name: configuration-variable
  type: http
  source: /configuration-variable/custom-greeting
